### ISSUE TITLE
Fullstory namespace conflict

### ISSUE THREAD

**Issue by TheTomRoelofs** [marcobaldo/ngx-fullstory#2]
I'm getting this error in the console:

`FullStory namespace conflict. Please set window["_fs_namespace"].`

Does this package support an easy way to change the namespace from fs to something else?

**Comment by beradrian** [comment]
After publishing a new version you can close this as well. @marcobaldo

**Comment by beradrian** [comment]
This is fixed in v2.0.3. Just use the config.fsNameSpace
