### ISSUE TITLE
Publish new version in npm

### ISSUE THREAD

**Issue by beradrian** [marcobaldo/ngx-fullstory#5]
I made a PR for upgrading to Angular 9, but I did a small mistake and left the name in package.json and projects/ngx-fullstory/package.json as @nibo-ai/ngx-fullstory. Could you please change it and publish to npm repo afterwards? Thank you!

**Comment by beradrian** [comment]
I created a new PR and changed the name back. Could you please publish the new version or add me as a contributor in the npm project and I can do it myself? @marcobaldo

**Comment by marcobaldo** [comment]
@beradrian I have added you as a contributor to the npm package. Thank you!

**Comment by beradrian** [comment]
v2.0.3 is published. Thanks!
