### ISSUE TITLE
Thoughts on matching the fullstory API directly?

### ISSUE THREAD

**Issue by DKirwan** [marcobaldo/ngx-fullstory#6]
Hi there,

I see that this wrapper uses the term `login` instead of `identify`, and it doesn't expose a method to track custom events.

I wanted to hear your thoughts on matching the SDK functions in this wrapper. It would be a breaking change, requiring a major version bump, but I think it would be good, and it would mean that my team can use it.

I'd be happy to make the changes, but I wanted to check with you before spending time on it.

**Comment by marcobaldo** [comment]
@DKirwan happy to accommodate the changes. Currently there is also an outstanding request to rename the package and publish to npm.

**Comment by DKirwan** [comment]
Great, thanks. It will likely be a couple weeks before I, or one of my colleagues, can get to this but we'll reference this issue in the pull request.

**Comment by beradrian** [comment]
To not introduce breaking changes you can make identify as an alias for login.

**Comment by beradrian** [comment]
After merging PR #8 could you please test that your issue is fixed? Thanks!

**Comment by beradrian** [comment]
Please check now. Thanks!

**Comment by beradrian** [comment]
I would propose to close this issue if no other details are provided. Thanks!
